### ISSUE TITLE
starting up textadept with this plugin generates stack overflow

### ISSUE THREAD

**Issue by Nanoc-ice** [jugglerchris/textadept-vi#36]
With the version 11.0_beta_2 for MacOS I am getting this in the message buffer and sometimes it takes a really long time to actually display the window.

..0_beta_2.macOS/Textadept.app/Contents/Resources/init.lua:52: stack overflow

When I comment out the inclusion of the textadept-vi plugin in my init.lua this message is not generated and it comes up quick.   I pulled the latest from the master branch with the same results.  Thoughts?

**Comment by Nanoc-ice** [comment]
Does the same thing with the latest release of 11.0.

**Comment by jugglerchris** [comment]
Hi,
There's an interaction between textadept-vi's key handling and some code in Textadept to warn about out of date keymaps.
If you add this line to your init.lua:
```lua
_NOCOMPAT = true
```
that should fix it.

However now that you mention it, it would seem like a good idea to add that to `textadept-vi` itself rather than expect users to do it, especialy now TA 11 has been released.  I'll do that in a few days (or happy to merge a PR before that), but setting `_NOCOMPAT` in your init.lua should be fine.

**Comment by Nanoc-ice** [comment]
Yes, that does indeed work.  I don’t have knowledge of the source base or plugins so I wonder if this impacts any other code or plugins?

**Comment by jugglerchris** [comment]
I don't think it's likely to affect many - textadept-vi is affected because there are some dynamic keypress handlers to cope with some complex vi behaviour.

I've re-opened as I think it is an issue - I'll push the fix shortly.
