### ISSUE TITLE
Leaving and re-entering vi mode

### ISSUE THREAD

**Issue by mfxmfx** [jugglerchris/textadept-vi#9]
Hi,

sorry for the possibly dumb question, but is there any way to fully leave vi mode (returning to standard textadept mode/bindings) and bind a key to re-enter it? The docs are a little bit sparse on this.

Thanks!

**Comment by jugglerchris** [comment]
Hi,

By default textadept-vi takes over the main keymap, and doesn't save the previous one - once it was working well enough I haven't had a need to go back.  :-)

There is an undocumented (and not recently tested, so it may not work) option to use a separate key mode rather than taking over the default key map, by editing vi_mode.lua and changing the value of M.vi_global (near the top) to false.  If that works, then mapping a key to set keys.MODE = nil would get out of vi mode.

If it's actually useful, though, it shouldn't be too hard to add a proper "disable vi" function/command.

Chris

**Comment by mfxmfx** [comment]
Hi Chris,

many thanks for the quick feedback - unfortunately I've already hit a few issues, so I will get more 
famliar with the default vi_global setting first.

~Markus

**Comment by jugglerchris** [comment]
Sorry about any issues - do please raise them and I'll look into them!

**Comment by jugglerchris** [comment]
Hi,
There's now a function `vi_mode.restore_keymap()`, which undoes the keymap changes, and a corresponding `vi_mode.install_keymap()` which puts it back to vi bindings.

Please re-open (or raise a new issue) if there are any problems.

Chris
